### ISSUE TITLE
How do I create dictionaries?

### ISSUE THREAD

**Issue by chayanroyc** [LucaCappelletti94/dictances#1]
I was trying to pass two numpy arrays in to the function. It gives an attribute error. What should I do? Thanks.

**Comment by LucaCappelletti94** [comment]
Hi, could you provide a simple snippet of code that can help me reproduce and debug this error?

Thanks!

**Comment by chayanroyc** [comment]
Hi! Thanks a lot for responding. Here is my code snippet.
```python
bhattacharyya(intmodel,bhobsaod)
```
With the exception being:
```bash
Traceback (most recent call last):
  File "C:\Users\acer\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-276-fcdb96960823>", line 1, in <module>
    bhattacharyya(intmodel,bhobsaod)
  File "C:\Users\acer\Anaconda3\lib\site-packages\dictances\bhattacharyya.py", line 22, in bhattacharyya
    return -log(bhattacharyya_coefficient(a, b))
  File "C:\Users\acer\Anaconda3\lib\site-packages\dictances\bhattacharyya.py", line 12, in bhattacharyya_coefficient
    for k, small_value in small.items():
AttributeError: 'numpy.ndarray' object has no attribute 'items'
```

I had another question. Can we use these distance methods to evaluate if a model data fits the true data well?

**Comment by LucaCappelletti94** [comment]
I need also how you created the data, or a portion of them.

**Comment by chayanroyc** [comment]
the two arrays are numpy arrays in the form, 
```
use python array([0.23546  , 0.20878  , 0.187    , ................])
```

**Comment by LucaCappelletti94** [comment]
Oh ok, but then I don't see why you'd need to use dictances: this is a library for distances between dictionaries as hashmaps. If you don't have an hashmap problem, it might be best to just use the distances from numpy.

If nonetheless you want to convert you numpy arrays to dictionaries you can do it as follows:
```
my_dict = dict(enumerate(my_numpy_array))
```
