### ISSUE TITLE
Tag new releases v1.5.1 - v1.5.6

### ISSUE THREAD

**Issue by ShamrockLee** [LucaCappelletti94/dictances#10]
Recent releases on PyPI, namely version 1.5.1 to 1.5.6, doesn't have a Git tag in this GitHub repository. A Git tag would be helpful for package tools and for users to download a specific version.

BTW, thank you for these great projects! They save my final report!

**Comment by LucaCappelletti94** [comment]
Where can I learn more about Git tags? I've never heard of that.

**Comment by ShamrockLee** [comment]
There are tags in this repository, and I had thought that you added them.

Tagging can be done from the command line via `git tag`.

2.6 Git Basics - Tagging
https://git-scm.com/book/en/v2/Git-Basics-Tagging

`git tag` man page
https://git-scm.com/docs/git-tag

The GitHub releases are based on Git tags. When creating a releases, it would ask you to either choose a tag or create one. Here's how to do that in the GitHub webpage:

Managing releases in a repository - GitHub Doc
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

Screenshots of previous tags in this project:

![Screenshot 2023-06-01 at 00-16-57 LucaCappelletti94_dictances Distances and divergences between distributions implemented in the best way I found in python](https://github.com/LucaCappelletti94/dictances/assets/44064051/f3cd1602-c468-45ce-8332-d6889ae788e4)

![Screenshot 2023-06-01 at 00-17-33 LucaCappelletti94_dictances Distances and divergences between distributions implemented in the best way I found in python](https://github.com/LucaCappelletti94/dictances/assets/44064051/67946a61-dffc-448e-b296-2752fb162e7f)

**Comment by LucaCappelletti94** [comment]
Ah those, sure. I never found any particular use for them, and while I had automated the publication of the tags a while back at some point it broke and I could not be bothered to fix it.

**Comment by LucaCappelletti94** [comment]
I have made tags for all recent versions that are allowed through GitHub interface - I am not sure how to do the same for the earlier ones. Are these enough or do you also need the earlier ones?

**Comment by ShamrockLee** [comment]
Thanks a lot! That will be helpful in my use case (I'm using [Nix Flakes](https://serokell.io/blog/practical-nix-flakes) and [dream2nix](https://github.com/nix-community/dream2nix)).
