### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DanStein91** [LucaCappelletti94/dictances#2]
Hello,

I was trying to use cosine and euclidean functions to find the similarity/distance between 2 documents (text). And I got the following error:
AttributeError: 'list' object has no attribute 'items'
Do I have to process this text to turn it to something else? 

Thanks,

Dan

**Comment by LucaCappelletti94** [comment]
Hello, could you please add an example of code that raises your issue?

Thanks!

**Comment by DanStein91** [comment]
I was trying to do the similarity between two different documents (in this case tweets) using cosine and euclidean similarity functions. 

a = "first text example"
b = "second text example"
print(cosine(a, b))

In order to get the similarity score do we have to vectorize it/ tf-idf, or does it only work with numbers.

**Comment by LucaCappelletti94** [comment]
Dictances is a python library to determine distance between dictionaries. You most probably want to use [sklearn TFIDF](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) and [pairwise cosine distance](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_distances.html).
