### ISSUE TITLE
distribution divergences are not commutative, so the sort function is unnecessary 

### ISSUE THREAD

**Issue by puneetsl** [LucaCappelletti94/dictances#4]
for example
`KLD(p, q) != KLD(q, p)` 
so the sort function should be removed before calculating divergence

**Comment by LucaCappelletti94** [comment]
On it!

**Comment by LucaCappelletti94** [comment]
The current solution should be correct, I think. Can you let me know your opinion about it? If you approve of it, I'll publish it to PyPI.

**Comment by puneetsl** [comment]
I think this should fix it. 👍 
Thanks for really quick response time 😄

**Comment by LucaCappelletti94** [comment]
I have published on Pypi the new version of the package (1.5.3). Let me know if it installs correctly and executes as you expect.

**Comment by puneetsl** [comment]
It worked for me! 
I'll be closing this issue, Thanks 😄
