### ISSUE TITLE
Provide Samples for use cases of Each Distance?

### ISSUE THREAD

**Issue by khanfarhan10** [LucaCappelletti94/dictances#5]
Perhaps improve the documentation by providing sample examples for use cases of Each Distance?

**Comment by LucaCappelletti94** [comment]
Helll @khanfarhan10 , could you go more into details or provide an example of what would you expect?

Thanks!

**Comment by khanfarhan10** [comment]
That is the problem :
So perhaps the uses for each function should be more well documented with samples such as taking random values
<code>
from dictances import bhattacharyya

import numpy as np

np.random.seed(42)

rows,cols= (10,20)
array_1 = np.random.rand(rows, cols)
array_2 = np.random.rand(rows, cols)

convert_to_dict1 = dict(enumerate(array_1))
convert_to_dict2 = dict(enumerate(array_2))
bhattacharyya(convert_to_dict1,convert_to_dict2)

"""
OUTPUT
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-08c1aa321f25> in <module>()
----> 1 bhattacharyya(convert_to_dict1,convert_to_dict2)

1 frames
/usr/local/lib/python3.6/dist-packages/dictances/bhattacharyya.py in bhattacharyya(a, b)
     45     Return the Bhattacharyya distance beetween the given dictionaries.
     46     
---> 47     distance = -np.log(bhattacharyya_coefficient(a, b))
     48     if np.isinf(distance):
     49         return 0

/usr/local/lib/python3.6/dist-packages/dictances/bhattacharyya.py in bhattacharyya_coefficient(a, b)
     25     for k, small_value in small.items():
     26         try:
---> 27             total += sqrt(big_get(k) * small_value)
     28         except KeyError:
     29             pass

TypeError: only size-1 arrays can be converted to Python scalars
"""
</code>

**Comment by LucaCappelletti94** [comment]
Sorry to be dense, I am not understanding yet your point. Could you clarify the following points, so that I can best understand what needs to be added to the documentation?

The methods are all tested and there is an usage example for each one in there. Furthermore, in the readme there are a couple examples that apply to every use case.

In your example, you have a dictionary of Numpy arrays. I fail to see why that is relevant to this library, as the library only handles discrete distributions described as dictionaries. If it is possible to describe the distributions as dense arrays, using dictionaries would be relatively meaningless and terribly slower.

Thank you!

**Comment by khanfarhan10** [comment]
Apparently I can't understand why the above example that I provided throws an error?

**Comment by Dejivi** [comment]
Hi @LucaCappelletti94 , thanks for the library, however, how can i compute the bhattacharyya ? what is the format of the input? It is quite non-intuitive

bhattacharyya({a:[1, 2, 3]},{b: [1, 2, 3]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined

Please can you provide more infor about this?

**Comment by LucaCappelletti94** [comment]
The Dictances library is meant as a fast way to compute distances between points in space described by dictionaries (hence the dict in the name). Such dictionaries are the only fast solution when dealing with sparse discrete distributions, which cannot often be represented with common numpy vectors, as it would contain a significant number of zeros.

I will add a more complete usage example in the main README illustrating the use cases.

**Comment by LucaCappelletti94** [comment]
I have updated the README. I hope it will clear how to use the library.
