### ISSUE TITLE
Problem with the bhattacharyya distance calculation

### ISSUE THREAD

**Issue by Dejivi** [LucaCappelletti94/dictances#6]
Hello!

Thanks for the library. I have some questions about the library. 
The definition of the bhattacharyya distance says that the distance must satisfy the following conditions:

d(x, y) ≥ 0 (non-negativity)
d(x, y) = 0 if and only if x = y (identity of indiscernibles. Note that condition 1 and 2 together produce positive definiteness)
d(x, y) = d(y, x) (symmetry)
d(x, z) ≤ d(x, y) + d(y, z) (subadditivity / triangle inequality).

I tried 
`query_p = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
>>> bhattacharyya(query_p, query_p)
-2.302585092994046`
This value is negative and you can see that both argument are the same, this means that the result should have been zero. 
Please can you explain what i am missing? 

Please can you specify what the right syntax is when it comes to using the bhattacharyya function, the syntax and the format of the input. Thanks

Thanks

**Comment by LucaCappelletti94** [comment]
Hello @Dejivi. As you surely know, the [Bhattacharyya distance](https://en.wikipedia.org/wiki/Bhattacharyya_distance) is **only defined for probability distributions**. That is, it does not make sense to use it for values that **do not sum to 1**.

I have prepared a small [Google Colab Notebook](https://colab.research.google.com/drive/1ON6NvjAi71_Ug5KIxNqWiDZd1qcaMRaZ?usp=sharing) for you to try.

I report here the content of the notebook for practicality:

```python
from dictances import bhattacharyya

a = {
    "event_1": 0.4,
    "event_2": 0.1,
    "event_3": 0.2,
    "event_4": 0.3,
}

b = {
    "event_1": 0.1,
    "event_2": 0.2,
    "event_3": 0.2,
    "event_4": 0.5,
}

assert sum(a.values()) == 1.0
assert sum(b.values()) == 1.0
assert bhattacharyya(a, a) == 0.0
assert bhattacharyya(b, b) == 0.0

bhattacharyya(a, b)
# >>> 0.07394831782125172
```
