### ISSUE TITLE
Continuous  Data

### ISSUE THREAD

**Issue by tasnimul-unipotsdam** [LucaCappelletti94/dictances#7]
HI, Thanks for your library. can I use your Bhattacharyya distance, Kullback–Leibler distance function for continuous data?

**Comment by LucaCappelletti94** [comment]
Hi, this is a library for describing those distances across discrete distributions represented as dictionaries, hence the `dict` in `dictances`. What do you mean by "continuous data"? If you are referring to "continuous distribution, " those would require the definition of the KL on the integral and are way outside this library's scope.
