### ISSUE TITLE
Cannot pip dictances

### ISSUE THREAD

**Issue by premmotgi** [LucaCappelletti94/dictances#8]
$ pip install dictances
Collecting dictances
  Using cached dictances-1.5.5.tar.gz (8.3 kB)
ERROR: Could not find a version that satisfies the requirement support_luca (from dictances) (from versions: none)
ERROR: No matching distribution found for support_luca (from dictances)

**Comment by LucaCappelletti94** [comment]
Thank you for reporting this error, that's a typo. Let me fix it.

**Comment by LucaCappelletti94** [comment]
Done!
