### ISSUE TITLE
Dimension's question

### ISSUE THREAD

**Issue by SergioPovoli** [LucaCappelletti94/dictances#9]
Ciao Luca,
I have a stupid question about input size (I'm working with Bhattacharyya distance):
Should the input dimensions be the same size?

Thanks for your work! 

Grazie!

**Comment by LucaCappelletti94** [comment]
You mean, dictionaries of the same length?

**Comment by SergioPovoli** [comment]
Yes!

**Comment by LucaCappelletti94** [comment]
Yes, keys missing in one of the two dictionaries are treated as zeros, if I recall correctly. If it is causing any errors please let me know, I'll look into it later today

**Comment by SergioPovoli** [comment]
Ok, thanks. 
No runtime error found: I will go deeper into this topic because I have two different sizes of dictionaries full of value bw/ 0-1, but the Bhattacharyya coefficient is not bounded bw/ 0-1.

**Comment by LucaCappelletti94** [comment]
Please post an example to replicate the issue.

**Comment by SergioPovoli** [comment]
Do you find some problems in this code ? 

I found that the problem is not dict dimension. 

```
a = [0.4,0.1,0.2,0.3]
b = [0.1,0.2,0.2,0.5]
a_dict = dict(enumerate(a))
b_dict = dict(enumerate(b))

print(f"{bhattacharyya_coefficient(a_dict,b_dict)=}")


#OUTPUT 
# bhattacharyya_coefficient(a_dict,b_dict)=0.9287196908580513

from dictances import bhattacharyya_coefficient

a = [0.34523,0.32523,0.1,0.21341,0.87]
b = [0.34523, 0.32523,0.1,0.21341,0.87]

a_dict = dict(enumerate(a))
b_dict = dict(enumerate(b))

print(f"{bhattacharyya_coefficient(a_dict,b_dict)=}")

#OUTPUT
# bhattacharyya_coefficient(a_dict,b_dict)=1.8538700000000001

```

**Comment by LucaCappelletti94** [comment]
[Bhattacharyya](https://en.wikipedia.org/wiki/Bhattacharyya_distance) is defined for probability distributions. Those dictionaries do not sum to `1.0`.

```python
assert sum([0.34523,0.32523,0.1,0.21341,0.87]) == 1.0
assert sum([0.34523, 0.32523,0.1,0.21341,0.87]) == 1.0
```

**Comment by SergioPovoli** [comment]
Thanks
